app:
  name: DefenseAgainstTheDarkArts
  version: 0.0.1
  debug: false
  secret_key: ssshhh-my-api-key-ap2394789d
server:
  host: 0.0.0.0
  port: 8080
database:
  engine: postgresql
  host: db.hogwarts.edu
  port: 5432
  username: dobby
  password: sssshhh-secret-database-password
  name: public
  pool_size: 10
logging:
  level: info
  format: json
  output: logs/app.log
