schemas = {
    "book": {
        "api_endpoint": "v1/books",
        "attributes": [
            "slug",
            "title",
            "summary",
            "author",
            "release_date",
            "dedication",
            "pages",
            "cover",
            "wiki",
        ],
    },
    "chapter": {
        "api_endpoint": "v1/books/{rel_id}/chapters",
        "id_ref": "book",
        "attributes": [
            "slug",
            "title",
            "order",
            "summary",
        ],
    },
    "character": {
        "api_endpoint": "v1/characters",
        "api_query": {"page[size]": 100},
        "attributes": [
            "slug",
            "name",
            "born",
            "died",
            "gender",
            "species",
            "height",
            "weight",
            "hair_color",
            "eye_color",
            "skin_color",
            "blood_status",
            "marital_status",
            "nationality",
            "animagus",
            "boggart",
            "house",
            "patronus",
            "image",
            "wiki",
        ],
        "array_attributes": [
            "alias_names",
            "family_members",
            "jobs",
            "romances",
            "titles",
            "wands",
        ],
    },
    "movie": {
        "api_endpoint": "v1/movies",
        "attributes": [
            "slug",
            "title",
            "summary",
            "release_date",
            "running_time",
            "budget",
            "box_office",
            "rating",
            "trailer",
            "poster",
            "wiki",
        ],
        "array_attributes": [
            "directors",
            "screenwriters",
            "producers",
            "cinematographers",
            "editors",
            "distributors",
            "music_composers",
        ],
    },
    "potion": {
        "api_endpoint": "v1/potions",
        "api_query": {"page[size]": 100},
        "attributes": [
            "slug",
            "name",
            "effect",
            "side_effects",
            "characteristics",
            "time",
            "difficulty",
            "ingredients",
            "inventors",
            "manufacturers",
            "image",
            "wiki",
        ],
    },
    "spell": {
        "api_endpoint": "v1/spells",
        "api_query": {"page[size]": 100},
        "attributes": [
            "slug",
            "name",
            "incantation",
            "category",
            "effect",
            "light",
            "hand",
            "creator",
            "image",
            "wiki",
        ],
    },
}
